#import "src/includes/gfx/font/a.bin"
#import "src/includes/gfx/font/b.bin"
#import "src/includes/gfx/font/c.bin"
#import "src/includes/gfx/font/d.bin"
#import "src/includes/gfx/font/e.bin"
#import "src/includes/gfx/font/f.bin"
#import "src/includes/gfx/font/g.bin"
#import "src/includes/gfx/font/h.bin"
#import "src/includes/gfx/font/i.bin"
#import "src/includes/gfx/font/j.bin"
#import "src/includes/gfx/font/k.bin"
#import "src/includes/gfx/font/l.bin"
#import "src/includes/gfx/font/m.bin"
#import "src/includes/gfx/font/n.bin"
#import "src/includes/gfx/font/o.bin"
#import "src/includes/gfx/font/p.bin"
#import "src/includes/gfx/font/q.bin"
#import "src/includes/gfx/font/r.bin"
#import "src/includes/gfx/font/s.bin"
#import "src/includes/gfx/font/t.bin"
#import "src/includes/gfx/font/u.bin"
#import "src/includes/gfx/font/v.bin"
#import "src/includes/gfx/font/w.bin"
#import "src/includes/gfx/font/x.bin"
#import "src/includes/gfx/font/y.bin"
#import "src/includes/gfx/font/z.bin"

; special characters
Hyphen:
#import	"src/includes/gfx/font/hyphen.bin"
Space:
#import	"src/includes/gfx/font/space.bin"
Period:
#import	"src/includes/gfx/font/period.bin"
LeftBracket:
#import	"src/includes/gfx/font/leftbracket.bin"
RightBracket:
#import	"src/includes/gfx/font/rightbracket.bin"

Numbers:
#import "src/includes/gfx/font/0.bin"
#import "src/includes/gfx/font/1.bin"
#import "src/includes/gfx/font/2.bin"
#import "src/includes/gfx/font/3.bin"
#import "src/includes/gfx/font/4.bin"
#import "src/includes/gfx/font/5.bin"
#import "src/includes/gfx/font/6.bin"
#import "src/includes/gfx/font/7.bin"
#import "src/includes/gfx/font/8.bin"
#import "src/includes/gfx/font/9.bin"